// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorrentGrease.Data;

namespace TorrentGrease.Data.Migrations
{
    [DbContext(typeof(TorrentGreaseDbContext))]
    [Migration("20191214205703_InitialTorrentStatisticsSchema")]
    partial class InitialTorrentStatisticsSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("TorrentGrease.Shared.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("TorrentGrease.Shared.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LogicalOperator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolicyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("TorrentGrease.Shared.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(300);

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("TorrentGrease.Shared.TorrentStatistics.Torrent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesOnDisk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalUploadInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasInClientOnLastScan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash");

                    b.ToTable("Torrent");
                });

            modelBuilder.Entity("TorrentGrease.Shared.TorrentStatistics.TorrentUploadDeltaSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TorrentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalUploadInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackerUrlCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadDeltaSinceLastSnapshotInBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackerUrlCollectionId");

                    b.HasIndex("TorrentId", "DateTime");

                    b.ToTable("TorrentUploadDeltaSnapshot");
                });

            modelBuilder.Entity("TorrentGrease.Shared.TorrentStatistics.TrackerUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackerUrlCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackerUrlCollectionId");

                    b.ToTable("TrackerUrl");
                });

            modelBuilder.Entity("TorrentGrease.Shared.TorrentStatistics.TrackerUrlCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CollectionHash")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("TrackerUrlCollection");
                });

            modelBuilder.Entity("TorrentGrease.Shared.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Tracker");
                });

            modelBuilder.Entity("TorrentGrease.Shared.TrackerPolicy", b =>
                {
                    b.Property<int>("TrackerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolicyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackerId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("TrackerPolicy");
                });

            modelBuilder.Entity("TorrentGrease.Shared.Action", b =>
                {
                    b.HasOne("TorrentGrease.Shared.Policy", null)
                        .WithMany("Actions")
                        .HasForeignKey("PolicyId");
                });

            modelBuilder.Entity("TorrentGrease.Shared.Condition", b =>
                {
                    b.HasOne("TorrentGrease.Shared.Policy", null)
                        .WithMany("Conditions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TorrentGrease.Shared.TorrentStatistics.TorrentUploadDeltaSnapshot", b =>
                {
                    b.HasOne("TorrentGrease.Shared.TorrentStatistics.Torrent", "Torrent")
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentGrease.Shared.TorrentStatistics.TrackerUrlCollection", "TrackerUrlCollection")
                        .WithMany()
                        .HasForeignKey("TrackerUrlCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TorrentGrease.Shared.TorrentStatistics.TrackerUrl", b =>
                {
                    b.HasOne("TorrentGrease.Shared.TorrentStatistics.TrackerUrlCollection", null)
                        .WithMany("TrackerUrls")
                        .HasForeignKey("TrackerUrlCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TorrentGrease.Shared.TrackerPolicy", b =>
                {
                    b.HasOne("TorrentGrease.Shared.Policy", "Policy")
                        .WithMany("TrackerPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentGrease.Shared.Tracker", "Tracker")
                        .WithMany("TrackerPolicies")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
