// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorrentGrease.Data;

namespace TorrentGrease.Data.Migrations
{
    [DbContext(typeof(TorrentGreaseDbContext))]
    [Migration("20190525211812_UniqueConstraintsOnOrder")]
    partial class UniqueConstraintsOnOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1");

            modelBuilder.Entity("TorrentGrease.Data.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionType")
                        .IsRequired();

                    b.Property<string>("Configuration");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<int?>("PolicyId");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConditionType")
                        .IsRequired();

                    b.Property<string>("Configuration");

                    b.Property<int>("LogicalOperator");

                    b.Property<int>("Order");

                    b.Property<int>("PolicyId");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("TrackerUrls");

                    b.HasKey("Id");

                    b.ToTable("Tracker");
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.TrackerPolicy", b =>
                {
                    b.Property<int>("TrackerId");

                    b.Property<int>("PolicyId");

                    b.HasKey("TrackerId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("TrackerPolicy");
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.Action", b =>
                {
                    b.HasOne("TorrentGrease.Data.Models.Policy", null)
                        .WithMany("Actions")
                        .HasForeignKey("PolicyId");
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.Condition", b =>
                {
                    b.HasOne("TorrentGrease.Data.Models.Policy", null)
                        .WithMany("Conditions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TorrentGrease.Data.Models.TrackerPolicy", b =>
                {
                    b.HasOne("TorrentGrease.Data.Models.Policy", "Policy")
                        .WithMany("TrackerPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentGrease.Data.Models.Tracker", "Tracker")
                        .WithMany("TrackerPolicies")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
