trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: './GitVersion.yml'

- task: Docker@2
  displayName: Docker build
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'flyingpianoman/torrent-grease'
    command: 'build'
    Dockerfile: 'TorrentGrease.Server/Dockerfile'
    buildContext: '.'
    arguments: '--build-arg VERSION=$(GitVersion.NugetVersion)'
    tags: |
      $(GitVersion.NugetVersion)
      latest

- task: BuildQualityChecks@6
  inputs:
    checkWarnings: true
    warningFailOption: 'fixed'
    warningThreshold: '0'
    warningFilters: '[wW]arning'

- task: Docker@2
  displayName: Docker push
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'flyingpianoman/torrent-grease'
    command: 'push'
    tags: |
      $(GitVersion.NugetVersion)
      latest

  