trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: gittools.gitversion-preview.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: Docker@2
  displayName: Docker build
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'flyingpianoman/torrent-grease'
    command: 'build'
    Dockerfile: 'TorrentGrease.Server/Dockerfile'
    buildContext: '.'
    tags: |
      $(GitVersion.NugetVersion)
      latest

- task: Docker@2
  displayName: Docker push
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'flyingpianoman/torrent-grease'
    command: 'push'
    tags: |
      $(GitVersion.NugetVersion)
      latest

  