trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: gittools.gitversion-preview.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'TorrentGrease'
    command: 'build'
    Dockerfile: 'TorrentGrease.Server/Dockerfile'
    buildContext: 'TorrentGrease.Server'
    tags: |
      $(GitVersion.NugetVersion)
      latest

- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'TorrentGrease'
    command: 'push'
    tags: |
      $(GitVersion.NugetVersion)
      latest

  