version: '3.4'

services:
  torrentgrease.server:
    container_name: torrent-grease
    build:
      context: ..
      dockerfile: TorrentGrease.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TORRENTCLIENT__USERNAME=usr
      - TORRENTCLIENT__PASSWORD=pwd
      - TORRENTCLIENT__TORRENTFILEDIRMAPPING=/transmission/config/torrents
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Filename=/app/data/TorrentGrease.db;Pooling=false #disable pooling so that we can swap out the sqlite file during testing
    volumes:
      - torrent-grease-data:/app/data
      - torrent-grease-logs:/app/logs
      - transmission-downloads:/downloads
      - transmission-secondary-downloads:/secondary-downloads
      - transmission-data:/transmission/config:ro #mount transmission config dir so we can access the torrent files
    ports:
      - 5656:5656
      - 5657:5657
      
  transmission: #username = usr, password = pwd
    container_name: transmission
    image: linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - transmission-data:/config
      - transmission-downloads:/downloads
      - transmission-secondary-downloads:/second-downloads
      - ./transmission/settings.json:/config/settings.json
    ports:
      - 9091:9091

  transmission-downloader:
    container_name: transmission-downloader
    image: linuxserver/transmission:2.94-r1-ls14
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - transmission-downloader-data:/config
    ports:
      - 9092:9091

  opentracker:
    container_name: my-tracker
    image: lednerb/opentracker-docker:latest

  #for ui testing. see also https://github.com/SeleniumHQ/docker-selenium#debugging
  selenium-firefox-standalone:
    image: selenium/standalone-firefox:4.1
    shm_size: '2gb'
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  torrent-grease-data:
  torrent-grease-logs:
  transmission-data:
  transmission-secondary-downloads:
  transmission-downloads:
  transmission-downloader-data:
